# Tenor functions with Pytorch

### Torch up your tensor game

The following 5 functions might empower you to navigate through your Deep Learning endeavours with Pytorch 
- torch.diag()
- torch.inverse()
- torch.randn()
- torch.zeros_like()
- torch.arange()

In [12]:
# Import torch and other required modules
import torch

## Function 1 - torch.diag()

Given some tensor, the above method returns it's diagonal(s).
The arguments to the function are as follows: 

### torch.diag(input, diagonal=0, output=None)

diagonal and output are optional paramenters.

1. If diagonal = 0, it is the main diagonal. (Principal diagonal)

2. If diagonal > 0, it is above the main diagonal.

3. If diagonal < 0, it is below the main diagonal.

In [13]:
# Example 1 - working 

scalar = torch.diag(torch.tensor([99]))
print('diagonal of scalar: ', scalar, '\n')     # returns scalar as is

vector = torch.diag(torch.tensor([1,2,3,4]))    # 1D tensor(Vector)
print('diagonal of vector: \n',vector)          # return square matrix with upper and lower 
                                                # triangular sections imputed with 0's

diagonal of scalar:  tensor([[99]]) 

diagonal of vector: 
 tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])


The above returns diagonals for scalars (the value itself) and vectors (in the form of a square matrix) 

In [14]:
# Example 2 - working
matrix = torch.diag(torch.tensor([[1,2,3],[4,5,6], [7,8,9]]))   # 3x3 matrix
print('diagonal of matrix: ', matrix, '\n')                     # returns the diagonal as is

mat1 = torch.diag(torch.tensor([[1,2,3],[4,5,6], [7,8,9]]), diagonal=1) 
print("mat1: ", mat1)   # returns diagonal above the principal diagonal of the matrix

diagonal of matrix:  tensor([1, 5, 9]) 

mat1:  tensor([2, 6])


The first example upon running simply returns the principal diagonal(PD) of the matrix.
The second example returns the diagonal above the PD of the matrix found the uppe triangular region.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
tensor = torch.diag(torch.randn(2,3,32,32))
print("tensor: ", tensor) #  tries to return diagonal of dim > 2 tensor but it isn't possible

RuntimeError: invalid argument 1: matrix or a vector expected at /opt/conda/conda-bld/pytorch_1587428190859/work/aten/src/TH/generic/THTensorMoreMath.cpp:319

Higher order tensors, i.e of dimensions above 2D aren't processed to return a diagonal as there can be numerous combinations of choosing one.

Matrix decompositons are invaluable in DL and this method can be availed of in computing for diagonals. An example of this use case would be in SVD (Singular Value Decomposition).

## Function 2 - torch.inverse()

torch.inverse(input, output=None)

Takes the inverse of the square matrix input. Batches of 2D tensors to this function would return tensor composed of individual inverses.

In [16]:
# Example 1 - working
tensor = torch.randn(3,3)  
torch.inverse(tensor)

tensor([[-2.2776, -3.0427, -0.3800],
        [-2.3478, -2.4279,  0.4850],
        [ 1.4135,  1.1857,  0.7018]])

Input should be in the form of a square matrix.

In [17]:
# Example 2 - working
tensor = torch.randn(3,3,3)
torch.inverse(tensor)

tensor([[[-9.1619e-01,  5.5130e+00, -1.0190e+00],
         [-6.1173e-01,  3.3946e-01, -1.0184e-01],
         [-2.2245e-01,  1.1796e+00,  2.4493e-01]],

        [[-8.0774e-01,  3.4553e-01, -5.4602e-01],
         [ 1.2442e+00, -1.0063e+00, -1.3885e+00],
         [ 1.7030e+00, -4.8550e-01, -5.1311e-01]],

        [[-1.0956e+01, -5.1598e+00, -5.0233e+00],
         [-1.3625e+02, -6.6060e+01, -5.5984e+01],
         [ 7.6127e+01,  3.7422e+01,  3.1592e+01]]])

The output tensor is a composition of individual inverses of the square matrix within the input matrix.

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
tensor = torch.randn(2,1,3)
torch.inverse(tensor)

RuntimeError: A must be batches of square matrices, but they are 3 by 1 matrices

Since the input tensor does not within itself contain batches of square matrices an error is raised for its non-invertibility (in this case).

Theta = (X^(T)X)^(-1).(X^(T)y) - is the normal equation for to find the parameter value for the Linear Regression algorithm.
The above torch.inverse() method can be used in its computation.

## Function 3 - torch.randn()

One of the most sort after functions to initialize a tensor to values of the normal distribution.

In [19]:
# Example 1 - working
scalar = torch.randn(1)
print('scalar: ', scalar, '\n')

vector = torch.randn(4)
print('vector: ', vector)

scalar:  tensor([-0.1876]) 

vector:  tensor([-0.7381,  0.0672, -0.8744,  0.0247])


Generates random values from the normal distribution and assignes it to the above 0 and 1 dimensional tensors.

In [20]:
# Example 2 - working
matrix = torch.randn(3,4)
print('matrix: ', matrix, '\n')

tensor = torch.randn(2,3,4)
print('tensor: ', tensor)

matrix:  tensor([[-0.2334,  0.2195, -0.0269,  0.7845],
        [-0.0449,  0.3875, -0.4712, -0.3937],
        [ 0.2163, -0.6599,  0.6185,  0.3160]]) 

tensor:  tensor([[[ 0.3230, -0.3016,  0.1979,  0.7916],
         [ 2.4401, -1.2157,  1.5754,  0.3830],
         [ 0.8756,  0.5772,  1.7545, -1.6390]],

        [[-0.1001, -1.3523,  0.0437,  1.1271],
         [ 0.6302,  1.1315,  0.1062,  0.7886],
         [ 1.9212, -0.2779, -1.2201,  0.6601]]])


Generates random values from the normal distribution and assignes it to the above 2 and 3 dimensional tensors.

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
tensor = torch.randn(-1,0,0)
print('tensor: ', tensor)

RuntimeError: Trying to create tensor with negative dimension -1: [-1, 0, 0]

Specified dimensions given to the torch.randn() method have to be Natural Numbers, which is obvious.

This method is handy when any tensor is to be initialized before performing any operations. Example of this would be to initialise the weights of the matrix of every layer of a neural network, randomly before performing backpropogation.

## Function 4 - torch.zeros_like()

The above method takes in a tensor, and given that input's dimensionalty it creates a corressponding tensor of the same shape, but with zeros all over.

In [22]:
# Example 1 - working
scal = torch.randn(1)
scal_zero = torch.zeros_like(scal)
print("zero_like for scalar: ", scal_zero, '\n')

vec = torch.randn(4)
vec_z = torch.zeros_like(vec)
print("zero_like for vector: ", vec_z)

zero_like for scalar:  tensor([0.]) 

zero_like for vector:  tensor([0., 0., 0., 0.])


Corresponding zero tensors are produced with the given input tensor.

In [23]:
# Example 2 - working
mat = torch.randn(2,3)
mat_z = torch.zeros_like(mat)
print("zero_like for matrix: ", mat_z, '\n')

ten = torch.randn(2,3,4)
ten_z = torch.zeros_like(ten)
print("zero_like for 3D tensor: ", ten_z, '\n')

zero_like for matrix:  tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

zero_like for 3D tensor:  tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) 



Explanation about example

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
ten_Z = torch.zeros_like(mat @ vec)
ten_z

RuntimeError: size mismatch, [2 x 3], [4] at /opt/conda/conda-bld/pytorch_1587428190859/work/aten/src/TH/generic/THTensorMath.cpp:193

torch_zeros_like() is a pretty full proof method, only a nonsensical input will give rise to error.

Handy way to initialize tensors to zeros with the demensions of another tensor.

## Function 5 - torch.arange()

Returns a 1D tensor of the interval of [start, end) with the given step size

In [25]:
# Example 1 - working
t = torch.arange(0, 5, 0.1)
t

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
        1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000,
        2.7000, 2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000,
        3.6000, 3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000,
        4.5000, 4.6000, 4.7000, 4.8000, 4.9000])

Returns a tensor with all the values within the range, given the step size.

In [26]:
# Example 2 - working
tt = torch.arange(0, 5, 0.01)

tt

tensor([0.0000, 0.0100, 0.0200, 0.0300, 0.0400, 0.0500, 0.0600, 0.0700, 0.0800,
        0.0900, 0.1000, 0.1100, 0.1200, 0.1300, 0.1400, 0.1500, 0.1600, 0.1700,
        0.1800, 0.1900, 0.2000, 0.2100, 0.2200, 0.2300, 0.2400, 0.2500, 0.2600,
        0.2700, 0.2800, 0.2900, 0.3000, 0.3100, 0.3200, 0.3300, 0.3400, 0.3500,
        0.3600, 0.3700, 0.3800, 0.3900, 0.4000, 0.4100, 0.4200, 0.4300, 0.4400,
        0.4500, 0.4600, 0.4700, 0.4800, 0.4900, 0.5000, 0.5100, 0.5200, 0.5300,
        0.5400, 0.5500, 0.5600, 0.5700, 0.5800, 0.5900, 0.6000, 0.6100, 0.6200,
        0.6300, 0.6400, 0.6500, 0.6600, 0.6700, 0.6800, 0.6900, 0.7000, 0.7100,
        0.7200, 0.7300, 0.7400, 0.7500, 0.7600, 0.7700, 0.7800, 0.7900, 0.8000,
        0.8100, 0.8200, 0.8300, 0.8400, 0.8500, 0.8600, 0.8700, 0.8800, 0.8900,
        0.9000, 0.9100, 0.9200, 0.9300, 0.9400, 0.9500, 0.9600, 0.9700, 0.9800,
        0.9900, 1.0000, 1.0100, 1.0200, 1.0300, 1.0400, 1.0500, 1.0600, 1.0700,
        1.0800, 1.0900, 1.1000, 1.1100, 

Returns a 1D tensor with all the values in the range with a smaller step size.

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
t = torch.arange(0, 5, 0.0000000000000000000000000000000000001)
t

RuntimeError: invalid size, possible overflow?

Cannot accomodate for high precision like the example above.

This function can be used to initiate a 1D tensor with alll values within an interval.

## Conclusion

By no means were these 5 functions the keystones to your Deep Learning endevours. But I think we're ready to start looking at linear models for Machine Learning - given at least this much knowledge and an ability to perform other inbetween manipulations.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Check out this blog for more on Matrices: https://jhui.github.io/2017/01/05/Deep-learning-linear-algebra/

In [28]:
!pip install jovian --upgrade --quiet

You should consider upgrading via the '/opt/conda/bin/python3.7 -m pip install --upgrade pip' command.


In [29]:
import jovian

<IPython.core.display.Javascript object>

In [ ]:
jovian.commit(project='01-tensor-operations-4abc9', environment=None)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
